INFO     pytest_result_log:plugin.py:122 --------------------Start: tests/test_selenium.py::test_web---------------------
WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:137 There was an error managing chromedriver (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)); using driver found in the cache
INFO     pytest_result_log:plugin.py:128 ---------------------End: tests/test_selenium.py::test_web----------------------