INFO     2025-07-31 19:25:29 [pytest_result_log:122]  : --------------------Start: tests/test_selenium.py::test_web---------------------
WARNING  2025-07-31 19:25:30 [selenium.webdriver.common.selenium_manager:137]  : There was an error managing chromedriver (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)); using driver found in the cache
INFO     2025-07-31 19:26:07 [pytest_result_log:190]  : test status is PASSED (tests/test_selenium.py::test_web): 
INFO     2025-07-31 19:26:07 [pytest_result_log:128]  : ---------------------End: tests/test_selenium.py::test_web----------------------
INFO     2025-07-31 19:26:07 [pytest_result_log:122]  : ---------------Start: tests/test_selenium.py::test_getRegionList----------------
ERROR    2025-07-31 19:26:18 [pytest_result_log:190]  : test status is FAILED (tests/test_selenium.py::test_getRegionList): TimeoutException
INFO     2025-07-31 19:26:18 [pytest_result_log:128]  : ----------------End: tests/test_selenium.py::test_getRegionList-----------------
